/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as RecordsIndexImport } from './routes/records/index'
import { Route as RecordsIdImport } from './routes/records/$id'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecordsIndexRoute = RecordsIndexImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => rootRoute,
} as any)

const RecordsIdRoute = RecordsIdImport.update({
  id: '/records/$id',
  path: '/records/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/records/$id': {
      id: '/records/$id'
      path: '/records/$id'
      fullPath: '/records/$id'
      preLoaderRoute: typeof RecordsIdImport
      parentRoute: typeof rootRoute
    }
    '/records/': {
      id: '/records/'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/records/$id': typeof RecordsIdRoute
  '/records': typeof RecordsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/records/$id': typeof RecordsIdRoute
  '/records': typeof RecordsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/records/$id': typeof RecordsIdRoute
  '/records/': typeof RecordsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/records/$id' | '/records'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/records/$id' | '/records'
  id: '__root__' | '/' | '/about' | '/records/$id' | '/records/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RecordsIdRoute: typeof RecordsIdRoute
  RecordsIndexRoute: typeof RecordsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RecordsIdRoute: RecordsIdRoute,
  RecordsIndexRoute: RecordsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/records/$id",
        "/records/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/records/$id": {
      "filePath": "records/$id.tsx"
    },
    "/records/": {
      "filePath": "records/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
